# Mathematica auto-messis
warning! denglish ahead

In [2]:
import numpy as np
import random

TODO:

- linear algebra
    - Skalarprodukt
        - Geometrische Interpretation ausarbeiten

- funktionen darstellen und manipulieren

- integrieren

- differenzieren

- approximating with taylor series

- kmeans clustering

- fitting a linear function on data points

## Skalarprodukt
Formel für n-dimensionalen Raum:
$$

\vec{a} \cdot \vec{b} = \sum_{i=1}^n a_i b_i, \quad \text{wobei } \vec{a} = (a_1, a_2, \dots, a_n) \text{ und } \vec{b} = (b_1, b_2, \dots, b_n).

$$

$$

a_i \text{ und } b_i \text{ sind hierbei Komponenten der Vektoren }

$$

Geometrische Interpretation:
$$
\mathbf{a} \cdot \mathbf{b} = \|\mathbf{a}\| \|\mathbf{b}\| \cos\theta
$$

In [3]:
# um das Skalarprodukt zweier Vektoren in python zu berechnen

n = 1000000
a = [random.random() for _ in range(n)] # we are initialising like this to show that data can be converted to an np.array
b = [random.random() for _ in range(n)] # we could of course just do 'a = np.random.random(n)" 
a = np.array(a) # unsere davor definierten arrays müssen wir zu einem numpy array umwandeln.
b = np.array(b) 

skalar = a @ b # or "np.dot(a,b)"

skalar

np.float64(250201.97633959382)

creating numpy arrays

In [6]:
# make it 2d
a = np.array([[4, 3.14, 99],[420,69,1337]])

print("Inhalt: ",a)
print("Typ: ", type(a))
print("Element Typ: ", a.dtype)

Inhalt:  [[   4.      3.14   99.  ]
 [ 420.     69.   1337.  ]]
Typ:  <class 'numpy.ndarray'>
Element Typ:  float64


In [14]:
# you can also set the datatype like so:
a = np.array([420691337420691337, 1337, 420], dtype = 'bool')
print("Data Type:", a.dtype)
print("a: ",a)
# Some Datatypes you can set it to: numpy.bool, numpy.int, numpy.float, numpy.complex

Data Type: bool
a:  [ True  True  True]


In [25]:
# arange(start,stop,steps)
a = np.arange(0,420,69)
print(a)
print("\n")

# makes one filled with zero
# zeros(shape)
a = np.zeros((4,4))
print(a)

print("\n")

# makes one filled with ones
# ones(shape)
a = np.ones((4,4))
print(a)

print("\n")

# identity matrix: 
# eye(shape)
a = np.eye(4)
print(a)

print("\n")


# gleichverteilte Werte zwischen min und max
# linspace(min,max,number of elements)
a = np.linspace(1, 2.14, 20)
print(a)



[  0  69 138 207 276 345 414]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[1.   1.06 1.12 1.18 1.24 1.3  1.36 1.42 1.48 1.54 1.6  1.66 1.72 1.78
 1.84 1.9  1.96 2.02 2.08 2.14]
